autoInstallPeers: true

allowBuilds:
  '@heroui/shared-utils': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true

overrides:
  fast-uri: '>=3.1.2'
  langsmith: '>=0.6.0'
  path-to-regexp: '>=8.4.0'

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

minimumReleaseAgeExclude:
  - '@swc/core-darwin-arm64@1.15.46'
  - '@swc/core-darwin-x64@1.15.46'
  - '@swc/core-linux-arm-gnueabihf@1.15.46'
  - '@swc/core-linux-arm64-gnu@1.15.46'
  - '@swc/core-linux-arm64-musl@1.15.46'
  - '@swc/core-linux-ppc64-gnu@1.15.46'
  - '@swc/core-linux-s390x-gnu@1.15.46'
  - '@swc/core-linux-x64-gnu@1.15.46'
  - '@swc/core-linux-x64-musl@1.15.46'
  - '@swc/core-win32-arm64-msvc@1.15.46'
  - '@swc/core-win32-ia32-msvc@1.15.46'
  - '@swc/core-win32-x64-msvc@1.15.46'
