---
# Based on https://github.com/bfra-me/works/blob/7217b637351a0b251d1d0c2158614210c7efdad0/.github/actions/pnpm-install/action.yaml
name: Setup pnpm
description: Setup pnpm and install dependencies

inputs:
  install-playwright:
    description: Install Playwright browsers
    default: 'false'
    required: false

runs:
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: pnpm
        node-version-file: .tool-versions

    - name: Install dependencies
      run: pnpm install ${{ steps.setup-node.outputs.cache-hit == 'true' && ' --prefer-offline' || '' }}
      shell: 'bash -Eeuo pipefail {0}'

    - if: ${{ inputs.install-playwright == 'true' }}
      name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps chromium
      shell: 'bash -Eeuo pipefail {0}'

  using: composite
