---
# Based on https://github.com/bfra-me/works/blob/7217b637351a0b251d1d0c2158614210c7efdad0/.github/actions/pnpm-install/action.yaml
name: Setup pnpm
description: Setup pnpm and install dependencies

inputs:
  install-playwright:
    description: Install Playwright browsers
    default: 'false'
    required: false

outputs:
  development-cache-hit:
    description: Whether the development cache was hit
    value: ${{ steps.cache-development.outputs.cache-hit }}

runs:
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        cache: pnpm
        node-version-file: .tool-versions

    - name: Install dependencies
      run: pnpm install ${{ steps.setup-node.outputs.cache-hit == 'true' && ' --prefer-offline' || '' }}
      shell: 'bash -Eeuo pipefail {0}'

    - if: ${{ inputs.install-playwright == 'true' }}
      name: Install Playwright browsers
      run: pnpm exec playwright install --with-deps chromium
      shell: 'bash -Eeuo pipefail {0}'

    - id: cache-development
      name: Restore development caches
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: development-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/*.ts', 'package.json', 'pnpm-workspace.yaml', '**/tsconfig*.json') }}
        path: |
          **/.cache
          **/.vite
          **/coverage
          **/tsconfig.tsbuildinfo
        restore-keys: development-cache-${{ runner.os }}-

  using: composite
