# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repository Settings

'on':
  push:
    branches: [main]
  schedule:
    - cron: '23 */12 * * *' # Every 12 hours on the 23rd minute.
  workflow_dispatch:

permissions: {}

jobs:
  update-repo-settings:
    name: Update Repository Settings
    runs-on: ubuntu-latest
    steps:
      - id: filter
        name: Filter Changed Files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: |
            settings:
              - .github/settings.yml
              - .github/workflows/update-repo-settings.yaml

      - id: get-workflow-access-token
        if: steps.filter.outputs.settings == 'true'
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        name: Get Workflow Access Token
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'administration:write, contents:read, issues:write'

      - if: steps.filter.outputs.settings == 'true'
        name: Update Repository Settings (${{ github.repository_owner }}/.github)
        uses: elstudio/actions-settings@v3-beta
        env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
